### ISSUE TITLE
FeaturesEnabled access_options not matches documentation and implementation

### ISSUE THREAD

**Issue by zaenk** [turnitin/turnitin-core-api#1]
In the openapi spec `access_options` are defined as follows: https://github.com/turnitin/turnitin-core-api/blob/main/tca-openapi.yaml#L1903-L1910

```yaml
        access_options:
          type: array
          items:
            type: string
            enum:
              - Native
              - CORE_API
              - Draft Coach
```

When using a feign client generated by the openapi generator based on the openapi spec in this repo this error is occurs:

```
Cannot construct instance of com.turnitin.client.model.FeaturesEnabled$AccessOptionsEnum, problem: Unexpected value 'NATIVE'
```

This is caused by the incorrect casing of the enum in the openapi specification.

Also, in the API docs, this attribute is documented differently:

Parameter | Description
-- | --
access_options | Indicates which access options (NATIVE, CORE_API, DRAFT_COACH) are available for this tenant

```json
    "access_options": [
        "NATIVE",
        "CORE_API",
        "DRAFT_COACH"
    ]
```

Please fix the API spec so. that matches the actual implementation.
